@startuml AQI Monitor Control Flow
start
partition Initialization {
:board;
:sensor;
:display;
:timer0=0, timer1=0;
}
partition "Main Loop" {
  partition "Read Sensor" {
    :counter = MAX_RETRY;
    repeat
      if (data available?) then (yes)
        :read serial;
        :process data;
        break;
      else (no)
        :decrement counter;
        :wait for 100ms;
      endif
    repeat while (counter>0?) is (yes) not (no)
  }
  if (counter>0) then (yes)

    partition Process {
      if (crc is new?) then (yes)
        :cache sample;
        if (now-timer0 > 5s?) then (yes)
          :average 5s cached samples;
          :timer0 = 0;
          if (now-timer1 > 1min?) then (yes)
            :average 1min cached samples;
            :store 1min average to flash;
            :timer1=0;
          else (no)
          endif
        else (no)
        endif
        if (no interactions for a DISPLAY time?) then (yes)
          :put display to sleep;
        else (no)
          partition Display {
            if (display text) then (yes)
              :display latest;
            elseif (display graph) then (yes)
              :graph from flash;
            else (no mode)
            endif
          }
        endif
      else (no)
      endif
    }

  else (no)
    :increment read errors;
    if (read errors > limit?) then (yes) 
      :reset sensor;
    else (no)
    endif
  endif

  if (no interactions for STANDBY time?) then (yes)
    :suspend sensor;
    :enable button interrupt;
    :put board to sleep;
    (Z)
    detach;
    (Z)
    :wakeup sensor;
  else (no)
    :wait for 100ms;
  endif

}

stop
@enduml
